# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: none

version = 1

[[annotations]]
path = "flatpak/*.patch"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "none"

[[annotations]]
path = "flatpak/pci.ids"
SPDX-License-Identifier = "GPL-2.0-or-later OR BSD-3-Clause"
SPDX-FileCopyrightText = "Maintained by Albert Pool, Martin Mares, and other volunteers from the PCI ID Project at https://pci-ids.ucw.cz/"

[[annotations]]
path = "flatpak/usb.ids"
SPDX-License-Identifier = "GPL-2.0-or-later OR BSD-3-Clause"
SPDX-FileCopyrightText = "Stephen J. Gowdy <linux.usb.ids@gmail.com>"
